### ISSUE TITLE
Linux is case sensitive

### ISSUE THREAD

**Issue by redsled84** [mc-carthy/lvStealthRl#1]
Hi, I'm not sure what system you're developing your game on but I ran into a small issue trying to run this game. 

```
Error: Could not open file assets/fonts/lineBeam.ttf. Does not exist.
```

IRC your assets/fonts/ font file is named ```Linebeam.ttf```.

**Comment by mc-carthy** [comment]
Thanks for picking that up Lucas!

Hopefully that's sorted now. Both on my filesystem and in my IDE it was shown as 'lineBeam.ttf', but as you say in the repo it was set as 'Linebeam.ttf'. I removed and re-imported it so it should work fine now.

Thanks again!

P.S. Developing on OSX which I believe is also case sensitive, I think for some reason git just didn't recognise the case change.

**Comment by redsled84** [comment]
👍
